const obj = {
  3: [
    {
      LeagueId: 67096,
      LeagueName: "",
      Enabled: false,
      LiveEnabled: false,
      OperatorId: null,
      DefaultDisable: false,
    },
    {
      LeagueId: 116,
      LeagueName: "",
      Enabled: false,
      LiveEnabled: false,
      OperatorId: null,
      DefaultDisable: false,
    },
    {
      LeagueId: 142,
      LeagueName: "",
      Enabled: false,
      LiveEnabled: false,
      OperatorId: null,
      DefaultDisable: false,
    },
  ],
  6: [
    {
      LeagueId: 308,
      LeagueName: "",
      Enabled: false,
      LiveEnabled: false,
      OperatorId: null,
      DefaultDisable: false,
    },
    {
      LeagueId: 27372,
      LeagueName: "",
      Enabled: false,
      LiveEnabled: false,
      OperatorId: null,
      DefaultDisable: false,
    },
    {
      LeagueId: 27501,
      LeagueName: "",
      Enabled: false,
      LiveEnabled: false,
      OperatorId: null,
      DefaultDisable: false,
    },
    {
      LeagueId: 13656,
      LeagueName: "",
      Enabled: false,
      LiveEnabled: false,
      OperatorId: null,
      DefaultDisable: false,
    },
    {
      LeagueId: 17319,
      LeagueName: "",
      Enabled: false,
      LiveEnabled: false,
      OperatorId: null,
      DefaultDisable: false,
    },
    {
      LeagueId: 44405,
      LeagueName: "",
      Enabled: false,
      LiveEnabled: false,
      OperatorId: null,
      DefaultDisable: false,
    },
    {
      LeagueId: 21744,
      LeagueName: "",
      Enabled: false,
      LiveEnabled: false,
      OperatorId: null,
      DefaultDisable: false,
    },
    {
      LeagueId: 22314,
      LeagueName: "",
      Enabled: false,
      LiveEnabled: false,
      OperatorId: null,
      DefaultDisable: false,
    },
  ],
};
