import {
  agileList,
  apiList,
  askQuestionList,
  blogList,
  bookList,
  careerList,
  comicList,
  communityList,
  computerScienceList,
  courseList,
  databaseList,
  docList,
  documentList,
  dotnetList,
  examList,
  generalList,
  gitList,
  glossaryList,
  hostingList,
  interactiveLearnList,
  jobList,
  libraryList,
  linuxList,
  marketingList,
  newsList,
  quizList,
  reactList,
  regexList,
  seoList,
  serviceList,
  sqlList,
  statisticsList,
  testList,
  toolList,
  tutorialList,
  typeScriptList,
  uiuxList,
  vpnList,
  websiteBuilderList,
  youtubeList,
  aiServiceList,
  diagramList,
  restList,
  collectionList,
  animationList,
  platformList,
  cheatSheetsList,
  publishList,
  designSystemList,
  remoteToolsList,
} from "./list";

export const routeList = [
  { path: "sql", text: "SQL", importList: sqlList },
  { path: "api", text: "API", importList: apiList },
  { path: "typescript", text: "TypeScript", importList: typeScriptList },
  { path: "dotnet", text: ".NET", importList: dotnetList },
  { path: "react", text: "React", importList: reactList },
  { path: "job", text: "Job Hunting", importList: jobList },
  { path: "career", text: "Career", importList: careerList },
  { path: "diagram", text: "Diagram", importList: diagramList },
  { path: "community", text: "Community", importList: communityList },
  { path: "aiService", text: "AI Service", importList: aiServiceList },
  {
    path: "themeBuilder",
    text: "Website Builder",
    importList: websiteBuilderList,
  },
  { path: "tool", text: "Tool", importList: toolList },
  { path: "docs", text: "Docs", importList: docList },
  { path: "news", text: "News", importList: newsList },
  { path: "general", text: "General", importList: generalList },
  { path: "database", text: "Database", importList: databaseList },
  { path: "vpn", text: "VPN", importList: vpnList },
  { path: "hosting", text: "Hosting", importList: hostingList },
  { path: "document", text: "Document", importList: documentList },
  { path: "ask", text: "Ask", importList: askQuestionList },
  {
    path: "computerScience",
    text: "Computer Science",
    importList: computerScienceList,
  },
  { path: "blog", text: "Blog", importList: blogList },
  { path: "tutorial", text: "Tutorial", importList: tutorialList },
  { path: "youtube", text: "Youtube", importList: youtubeList },
  { path: "courses", text: "Online Courses", importList: courseList },
  { path: "restapi", text: "REST API", importList: restList },
  { path: "book", text: "Book", importList: bookList },
  { path: "linux", text: "Linux", importList: linuxList },
  { path: "comic", text: "Comic", importList: comicList },
  {
    path: "interactive",
    text: "Interactive learning",
    importList: interactiveLearnList,
  },
  { path: "agile", text: "Agile", importList: agileList },
  { path: "exam", text: "Exam", importList: examList },
  { path: "library", text: "Library", importList: libraryList },
  { path: "statistics", text: "Statistics", importList: statisticsList },
  { path: "services", text: "Services", importList: serviceList },
  { path: "regex", text: "Regex", importList: regexList },
  { path: "quiz", text: "Quiz", importList: quizList },
  { path: "test", text: "Test", importList: testList },
  { path: "seo", text: "SEO", importList: seoList },
  { path: "glossary", text: "Glossary", importList: glossaryList },
  { path: "git", text: "Git", importList: gitList },
  { path: "marketing", text: "Marketing", importList: marketingList },
  { path: "uiux", text: "UI UX", importList: uiuxList },
  { path: "collection", text: "Collection", importList: collectionList },
  { path: "animation", text: "Animation", importList: animationList },
  { path: "platform", text: "Platform", importList: platformList },
  { path: "cheatsheet", text: "Cheat Sheet", importList: cheatSheetsList },
  { path: "publish", text: "Publish", importList: publishList },
  { path: "designSystem", text: "Design System", importList: designSystemList },
  { path: "remoteTools", text: "Remote Tools", importList: remoteToolsList },
  { path: "/", text: "Home", importList: null },
];
